### ISSUE TITLE
TWC_HOME

### ISSUE THREAD

**Issue by PeterAJansen** [IBM/LOA#2]
Thanks for releasing your code!  I have followed the instructions and get the following error when I run it (probably just some missing steps in the instructions?): 
```
(loa) peter@neutronium:~/github/LOA-ScienceWorld$ python train.py
Could not find TWC_HOME. Using default path...
Could not find DDLNN_HOME. Using default path...
Traceback (most recent call last):
  File "train.py", line 78, in <module>
    loa_agent.obtain_admissible_verb(
  File "/home/peter/github/LOA-ScienceWorld/loa_agent.py", line 200, in obtain_admissible_verb
    LogicalTWCQuantifier(difficulty_level,
  File "/home/peter/github/LOA-ScienceWorld/logical_twc.py", line 173, in __init__
    load_twc_game(difficulty_level,
  File "/home/peter/github/LOA-ScienceWorld/logical_twc.py", line 88, in load_twc_game
    game_file_names = game_file_names[game_no]
IndexError: list index out of range
```

Also, am I correct in that the AMR processor is required to run this model on different environments?  Is it possible to get access to it?

**Comment by daiki-kimura** [comment]
The default path for TWC_HOME is `games/twc/`
https://github.com/IBM/LOA/blob/main/logical_twc.py#L14

This error is happened if there is no game files in the folder, i think.
Please try the setup game codes (clone the commonsense-rl repo and copy the game files) in setup
https://github.com/IBM/LOA#setup


> Also, am I correct in that the AMR processor is required to run this model on different environments? Is it possible to get access to it?

Yes, if you want to try on the new environments, it needs the AMR server.
We are now planing to release the code for AMR soon, so please wait.

**Comment by daiki-kimura** [comment]
Thank you for trying our repo

The default path for TWC_HOME is `games/twc/`
https://github.com/IBM/LOA/blob/main/logical_twc.py#L14

This error is happened if there is no game files in the folder, i think.
Please try the setup game codes (clone the commonsense-rl repo and copy the game files) in setup
https://github.com/IBM/LOA#setup


> Also, am I correct in that the AMR processor is required to run this model on different environments? Is it possible to get access to it?

Yes, if you want to try on the new environments, it needs the AMR server.
We are now planing to release the code for AMR soon, so please wait.

**Comment by daiki-kimura** [comment]
We have added installation codes for setting up from amr and amr-cslogic
