### ISSUE TITLE
Broken AMR?

### ISSUE THREAD

**Issue by MathieuTuli** [IBM/LOA#3]
I do not have access to the provide AMR-CSLogic link found in the setup section however noted that there is this repo available: https://github.com/IBM/AMR-CSLogic. None the less, whether I use that repo or the cache `.pkl` file provided in the setup section, the training doesn't work. 

When using the cached `.pkl` provided, I get the following error on line 142 in [amr_parser.py](https://github.com/IBM/LOA/blob/main/amr_parser.py)
```
Exception: Need the AMR server for "On the dark carpet you can make out a clean red dress."
```

If I try to run the flask server instead with that other AMR-CSLogic repo I linked above, when it tries to process the same sentence (i.e. `On the dark carpet you can make out a clean red dress.`) then an exception occurs in the flask server:
```
loa/third_party/amr-cslogic/amr_verbnet_semantics/service/amr.py", line 25, in _get_parser
    from transition_amr_parser.parse import AMRParser
ModuleNotFoundError: No module named 'transition_amr_parser'
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
127.0.0.1 - - [14/Jan/2022 16:26:40] "GET /amr_parsing?text=On+the+dark+carpet+you+can+make+out+a+clean+red+dress. HTTP/1.1" 500 -

```

What is the fundamental purpose of the AMR and can these issues be avoided? Further, it seems that this AMR server only applies to the TWC game, how about other TextWorld games? How might we use this code for such games?

**Comment by MathieuTuli** [comment]
I found this repo: https://github.com/IBM/transition-amr-parser, which I believe is what is required to at least fix the `transition_amr_parser` import error. If that's the case though, you would need to install the `action-pointer` branch from that repo. But still, this results in import errors, specifically with the `fairseq_ext` package. So I'm a little lost as to what needs to be downloaded, what version/branch, etc., cause there seems to be a nest of dependencies not listed on the setup. Any help would be appreaciated.

**Comment by daiki-kimura** [comment]
Thank you for your feedback 
We are now trying to use the open-sourced amr-cslogic and prepare the installation guide, please wait a moment. Thank you

**Comment by daiki-kimura** [comment]
We have added installation codes for setting up from amr and amr-cslogic
