### ISSUE TITLE
Error in requirements.txt?

### ISSUE THREAD

**Issue by davebiagioni** [IBM/LOA#4]
First off, thanks for your efforts in putting this work out there! 

I was following the installation instructions and hit this error:

```
AttributeError: module 'cdd' has no attribute 'Matrix'
```

Digging into this, I believe your `requirements.txt` is meant to have `pycddlib` ([this pypi package](https://pypi.org/project/pycddlib/)) rather than `cdd` ([this pypi package](https://pypi.org/project/cdd/)).  I didn't open a PR because I don't know the version you're actually using -- there is no `pycddlib==0.1.4`.

Thank you!

**Comment by daiki-kimura** [comment]
Thank you for your trying.
I confirm `pycddlib` is required, I added `pycddlib==2.1.4`.
Thank you @davebiagioni
